### ISSUE TITLE
All images are outdated essue

### ISSUE THREAD

**Issue by usuisora** [DmitryIvanov92/formula-fe-test#1]
**In task 3**
 supposed to get not expired image(s) with description . **But**  instead ! The **all images are expired**! Check to ensure: **https://formula-test-api.herokuapp.com/menu** .
**Give me feedback here .** Thank you!

**Comment by justpetrovych** [comment]
@usuisora Sorry for the delay, it's already fixed in [commit c01012c](https://github.com/DmitryIvanov92/f1-test-api/commit/c01012ced2cc170872ef69a46dfdccc48ec14b01)
